/**
 * Docusaurus-to-Tome migration converter.
 *
 * Reads a Docusaurus project (docusaurus.config.js + sidebars.js + docs/),
 * converts components and configuration into Tome equivalents, and writes
 * the result to an output directory.
 */

import {
  readFileSync,
  existsSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  readdirSync,
  statSync,
} from 'fs';
import { join, relative, dirname, extname, basename } from 'path';
import matter from 'gray-matter';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type NavigationGroup = {
  group: string;
  pages: Array<string | NavigationGroup>;
};

export type MigrationResult = {
  pages: number;
  redirects: number;
  warnings: string[];
  convertedFiles: string[];
};

export type DocusaurusConfig = {
  title?: string;
  tagline?: string;
  url?: string;
  baseUrl?: string;
  favicon?: string;
  themeConfig?: {
    navbar?: {
      title?: string;
      logo?: { alt?: string; src?: string };
      items?: Array<{ label?: string; href?: string; to?: string; position?: string }>;
    };
    footer?: {
      style?: string;
      links?: Array<{ title?: string; items?: Array<{ label?: string; href?: string; to?: string }> }>;
    };
    colorMode?: {
      defaultMode?: string;
      disableSwitch?: boolean;
    };
  };
};

export type SidebarItem =
  | string
  | { type: 'doc'; id: string; label?: string }
  | { type: 'category'; label: string; items: SidebarItem[] }
  | { type: 'autogenerated'; dirName: string }
  | { type: 'link'; label: string; href: string };

export type SidebarsConfig = Record<string, SidebarItem[]>;

// ---------------------------------------------------------------------------
// Config parsing
// ---------------------------------------------------------------------------

/**
 * Parse a docusaurus.config.js file content using regex extraction.
 *
 * Handles both ESM (`export default { ... }`) and CJS (`module.exports = { ... }`)
 * formats. Uses regex since we cannot safely eval arbitrary config files.
 */
export function parseDocusaurusConfig(content: string): DocusaurusConfig {
  const config: DocusaurusConfig = {};

  // Extract title
  const titleMatch = content.match(/title\s*:\s*['"`]([^'"`]+)['"`]/);
  if (titleMatch) config.title = titleMatch[1];

  // Extract tagline
  const taglineMatch = content.match(/tagline\s*:\s*['"`]([^'"`]+)['"`]/);
  if (taglineMatch) config.tagline = taglineMatch[1];

  // Extract url
  const urlMatch = content.match(/\burl\s*:\s*['"`]([^'"`]+)['"`]/);
  if (urlMatch) config.url = urlMatch[1];

  // Extract baseUrl
  const baseUrlMatch = content.match(/baseUrl\s*:\s*['"`]([^'"`]+)['"`]/);
  if (baseUrlMatch) config.baseUrl = baseUrlMatch[1];

  // Extract favicon
  const faviconMatch = content.match(/favicon\s*:\s*['"`]([^'"`]+)['"`]/);
  if (faviconMatch) config.favicon = faviconMatch[1];

  // Extract navbar title from themeConfig.
  // Use indexOf-based extraction to avoid ReDoS-prone nested quantifiers.
  {
    const navbarIdx = content.indexOf('navbar');
    if (navbarIdx !== -1) {
      const braceIdx = content.indexOf('{', navbarIdx);
      if (braceIdx !== -1) {
        // Search for `title:` within a reasonable window after the opening brace
        const searchEnd = Math.min(braceIdx + 500, content.length);
        const navbarChunk = content.slice(braceIdx, searchEnd);
        const titleMatch = navbarChunk.match(/title\s*:\s*['"`]([^'"`]+)['"`]/);
        if (titleMatch) {
          config.themeConfig = config.themeConfig || {};
          config.themeConfig.navbar = config.themeConfig.navbar || {};
          config.themeConfig.navbar.title = titleMatch[1];
        }
      }
    }
  }

  // Extract navbar logo src.
  // Use indexOf to locate `logo` block, then regex within a bounded chunk.
  {
    const logoIdx = content.indexOf('logo');
    if (logoIdx !== -1) {
      const braceIdx = content.indexOf('{', logoIdx);
      if (braceIdx !== -1) {
        const searchEnd = Math.min(braceIdx + 500, content.length);
        const logoChunk = content.slice(braceIdx, searchEnd);
        const srcMatch = logoChunk.match(/src\s*:\s*['"`]([^'"`]+)['"`]/);
        if (srcMatch) {
          config.themeConfig = config.themeConfig || {};
          config.themeConfig.navbar = config.themeConfig.navbar || {};
          config.themeConfig.navbar.logo = { src: srcMatch[1] };
        }
      }
    }
  }

  // Extract colorMode defaultMode.
  // Use indexOf to locate `colorMode` block, then regex within a bounded chunk.
  {
    const colorModeIdx = content.indexOf('colorMode');
    if (colorModeIdx !== -1) {
      const braceIdx = content.indexOf('{', colorModeIdx);
      if (braceIdx !== -1) {
        const searchEnd = Math.min(braceIdx + 500, content.length);
        const colorModeChunk = content.slice(braceIdx, searchEnd);
        const modeMatch = colorModeChunk.match(/defaultMode\s*:\s*['"`]([^'"`]+)['"`]/);
        if (modeMatch) {
          config.themeConfig = config.themeConfig || {};
          config.themeConfig.colorMode = { defaultMode: modeMatch[1] };
        }
      }
    }
  }

  return config;
}

// ---------------------------------------------------------------------------
// Sidebar parsing
// ---------------------------------------------------------------------------

/**
 * Parse a sidebars.js file content using regex extraction.
 *
 * Handles both ESM and CJS formats. Extracts the sidebar object and
 * recursively parses categories, docs, and string entries.
 */
export function parseSidebarsConfig(content: string): SidebarsConfig {
  // Try to extract the sidebars object as JSON-like content.
  // Strip comments first.
  // Remove single-line comments, then block comments.
  // Block comment removal uses indexOf loop instead of regex to avoid ReDoS
  // with the `[\s\S]*?` pattern.
  // Remove single-line comments line by line to avoid any regex backtracking
  let cleaned = content.split('\n').map(line => {
    const idx = line.indexOf('//');
    return idx >= 0 ? line.slice(0, idx) : line;
  }).join('\n');
  {
    let result = '';
    let pos = 0;
    while (pos < cleaned.length) {
      const openIdx = cleaned.indexOf('/*', pos);
      if (openIdx === -1) {
        result += cleaned.slice(pos);
        break;
      }
      result += cleaned.slice(pos, openIdx);
      const closeIdx = cleaned.indexOf('*/', openIdx + 2);
      if (closeIdx === -1) {
        // Unclosed block comment — discard the rest
        break;
      }
      pos = closeIdx + 2;
    }
    cleaned = result;
  }

  // Find the main export (ESM or CJS) using indexOf to avoid ReDoS
  let objStr: string | null = null;
  const esmIdx = cleaned.indexOf('export default');
  const cjsIdx = cleaned.indexOf('module.exports');
  const startIdx = esmIdx >= 0 ? esmIdx : cjsIdx;

  if (startIdx >= 0) {
    const braceStart = cleaned.indexOf('{', startIdx);
    if (braceStart >= 0) {
      // Find matching closing brace
      let depth = 0;
      let end = braceStart;
      for (; end < cleaned.length; end++) {
        if (cleaned[end] === '{') depth++;
        else if (cleaned[end] === '}') { depth--; if (depth === 0) break; }
      }
      if (depth === 0) {
        objStr = cleaned.slice(braceStart, end + 1);
      }
    }
  }

  if (!objStr) return {};

  // Convert JS object literal to valid JSON:
  // - Add quotes around unquoted keys (line by line to avoid backtracking)
  // - Replace single quotes with double quotes
  // - Remove trailing commas
  // Quote unquoted keys: word followed by colon (per-line to limit backtracking scope)
  objStr = objStr.split('\n').map(line => {
    // Only quote keys that aren't already quoted
    return line.replace(/(?<=^|[{,\s])(\w+)(?=\s*:)/g, '"$1"');
  }).join('\n')
    .replace(/'/g, '"')
    .replace(/,\s*([}\]])/g, '$1');

  try {
    return JSON.parse(objStr) as SidebarsConfig;
  } catch {
    // If JSON parse fails, return empty – the content is too complex for
    // regex-based parsing (e.g. uses JS functions, requires, etc.)
    return {};
  }
}

/**
 * Convert parsed Docusaurus sidebar items into Tome NavigationGroup format.
 */
export function convertSidebarItems(
  items: SidebarItem[],
  docsDir?: string,
): Array<string | NavigationGroup> {
  const result: Array<string | NavigationGroup> = [];

  for (const item of items) {
    if (typeof item === 'string') {
      // Simple string reference – use as-is
      result.push(item);
    } else if (item.type === 'doc') {
      result.push(item.id);
    } else if (item.type === 'category') {
      const group: NavigationGroup = {
        group: item.label,
        pages: convertSidebarItems(item.items, docsDir),
      };
      result.push(group);
    } else if (item.type === 'autogenerated') {
      // For autogenerated sidebars, scan the directory if provided
      if (docsDir) {
        const dirPath = item.dirName === '.'
          ? docsDir
          : join(docsDir, item.dirName);
        if (existsSync(dirPath)) {
          const files = scanDocsDir(dirPath);
          for (const f of files) {
            const rel = relative(docsDir, f);
            const page = rel.replace(/\.(mdx?|md)$/, '');
            result.push(page);
          }
        }
      }
    }
    // type: 'link' items are external links; skip them in navigation
  }

  return result;
}

/**
 * Convert a full SidebarsConfig into Tome NavigationGroup array.
 */
export function convertDocusaurusSidebars(
  sidebars: SidebarsConfig,
  docsDir?: string,
): NavigationGroup[] {
  const groups: NavigationGroup[] = [];

  for (const [sidebarName, items] of Object.entries(sidebars)) {
    if (!Array.isArray(items)) continue;

    const converted = convertSidebarItems(items, docsDir);

    // If items are all top-level categories, flatten them as separate groups
    const allCategories = converted.every(
      (c) => typeof c !== 'string' && 'group' in c,
    );

    if (allCategories && converted.length > 0) {
      for (const c of converted) {
        if (typeof c !== 'string' && 'group' in c) {
          groups.push(c as NavigationGroup);
        }
      }
    } else {
      // Use the sidebar name as the group name
      groups.push({
        group: sidebarName.charAt(0).toUpperCase() + sidebarName.slice(1),
        pages: converted,
      });
    }
  }

  return groups;
}

// ---------------------------------------------------------------------------
// Full config conversion
// ---------------------------------------------------------------------------

/** Convert a parsed DocusaurusConfig into a Tome-compatible config object. */
export function convertDocusaurusConfig(
  docConfig: DocusaurusConfig,
  sidebars?: SidebarsConfig,
  docsDir?: string,
): Record<string, any> {
  const tome: Record<string, any> = {};

  // Name – prefer navbar title, fall back to site title
  const name = docConfig.themeConfig?.navbar?.title || docConfig.title;
  if (name) tome.name = name;

  // Logo
  if (docConfig.themeConfig?.navbar?.logo?.src) {
    tome.logo = docConfig.themeConfig.navbar.logo.src;
  }

  // Favicon
  if (docConfig.favicon) {
    tome.favicon = docConfig.favicon;
  }

  // Top navigation items from navbar
  const navItems = docConfig.themeConfig?.navbar?.items;
  if (navItems && navItems.length > 0) {
    const topNav = navItems
      .filter((item) => item.label && (item.href || item.to))
      .map((item) => ({
        label: item.label!,
        href: item.href || item.to || '',
      }));

    if (topNav.length > 0) {
      tome.topNav = topNav;
    }
  }

  // Navigation from sidebars
  if (sidebars) {
    const navigation = convertDocusaurusSidebars(sidebars, docsDir);
    if (navigation.length > 0) {
      tome.navigation = navigation;
    }
  }

  return tome;
}

// ---------------------------------------------------------------------------
// Content conversion helpers
// ---------------------------------------------------------------------------

/**
 * Convert Docusaurus-specific MDX syntax to Tome equivalents.
 *
 * Returns the converted string and a flag indicating whether the content
 * contains JSX (i.e. should be written as .mdx).
 */
export function convertDocusaurusContent(content: string): {
  converted: string;
  hasJsx: boolean;
} {
  let result = content;
  let hasJsx = false;

  // 1. Strip Docusaurus component imports ----------------------------------
  //    e.g. import Tabs from '@theme/Tabs';
  //         import TabItem from '@theme/TabItem';
  //         import anything from '@site/...'
  // Strip Docusaurus imports line by line to avoid regex backtracking
  result = result.split('\n').map(line => {
    const trimmed = line.trim();
    if (trimmed.startsWith('import ') && /from\s+['"]@(theme|site|docusaurus)\//.test(trimmed)) {
      return '';
    }
    return line;
  }).join('\n');

  // Also strip require-style imports
  result = result.split('\n').map(line => {
    const trimmed = line.trim();
    if (trimmed.startsWith('const ') && /require\(\s*['"]@(theme|site|docusaurus)\//.test(trimmed)) {
      return '';
    }
    return line;
  }).join('\n');

  // 2. Admonitions ---------------------------------------------------------
  //    :::note     → <Callout type="info">
  //    :::tip      → <Callout type="tip">
  //    :::info     → <Callout type="info">
  //    :::warning  → <Callout type="warning">
  //    :::danger   → <Callout type="error">
  //    :::caution  → <Callout type="warning">
  //    Optional title: :::note My Title → <Callout type="info" title="My Title">
  const admonitionMap: Record<string, string> = {
    note: 'info',
    tip: 'tip',
    info: 'info',
    warning: 'warning',
    danger: 'error',
    caution: 'warning',
  };

  // Match admonition blocks: :::type optional title\ncontent\n:::
  // The title must be on the same line as :::type (use [^\n] not . to avoid
  // matching across the newline).
  const admonitionRe = /^:::(note|tip|info|warning|danger|caution)(?:[^\S\n]+([^\n]+))?\n([\s\S]*?)^:::\s*$/gm;
  result = result.replace(admonitionRe, (_match, type: string, title: string, body: string) => {
    const calloutType = admonitionMap[type] || 'info';
    const trimmedBody = body.trimEnd();
    hasJsx = true;

    if (title && title.trim()) {
      return `<Callout type="${calloutType}" title="${title.trim()}">\n${trimmedBody}\n</Callout>`;
    }
    return `<Callout type="${calloutType}">\n${trimmedBody}\n</Callout>`;
  });

  // 3. Tabs / TabItem → Tome Tabs / Tab -----------------------------------
  //    <Tabs> stays the same (or add items prop)
  //    <TabItem value="x" label="Y">…</TabItem> → <Tab>…</Tab>

  // Extract tab labels and convert
  {
    const tabsStartTag = '<Tabs';
    let searchIdx = 0;

    while (true) {
      const startIdx = result.indexOf(tabsStartTag, searchIdx);
      if (startIdx === -1) break;

      // Find the matching </Tabs>
      const endTag = '</Tabs>';
      const endIdx = result.indexOf(endTag, startIdx);
      if (endIdx === -1) break;

      const fullBlock = result.slice(startIdx, endIdx + endTag.length);

      // Extract TabItem labels
      const labelRe = /<TabItem[^>]*label=["']([^"']+)["'][^>]*>/g;
      const labels: string[] = [];
      let labelMatch: RegExpExecArray | null;

      while ((labelMatch = labelRe.exec(fullBlock)) !== null) {
        labels.push(labelMatch[1]);
      }

      // Replace <TabItem ...> with <Tab> and </TabItem> with </Tab>
      let converted = fullBlock;
      converted = converted.replace(/<TabItem[^>]*>/g, '<Tab>');
      converted = converted.replace(/<\/TabItem>/g, '</Tab>');

      // Replace opening <Tabs...> with <Tabs items={[...]}>
      if (labels.length > 0) {
        const itemsStr = JSON.stringify(labels);
        converted = converted.replace(
          /<Tabs[^>]*>/,
          `<Tabs items={${itemsStr}}>`,
        );
      } else {
        converted = converted.replace(/<Tabs[^>]*>/, '<Tabs>');
      }

      result = result.slice(0, startIdx) + converted + result.slice(endIdx + endTag.length);
      searchIdx = startIdx + converted.length;
      hasJsx = true;
    }
  }

  // 4. Code blocks with title attribute -----------------------------------
  //    ```js title="example.js"  → ```js example.js
  result = result.replace(
    /```(\w+)\s+title=["']([^"']+)["']/g,
    '```$1 $2',
  );

  // 5. Strip @site/ path references in images/links ----------------------
  result = result.replace(/@site\//g, '');

  // 6. Check for remaining JSX if we haven't flagged it yet
  if (!hasJsx) {
    hasJsx = /<[A-Z][\w.]*[\s>]/.test(result);
  }

  // Clean up multiple consecutive blank lines from stripped imports
  result = result.replace(/\n{3,}/g, '\n\n');

  return { converted: result, hasJsx };
}

// ---------------------------------------------------------------------------
// File-system helpers
// ---------------------------------------------------------------------------

/** Recursively walk a directory, returning all file paths. */
function walkDir(dir: string, fileList: string[] = []): string[] {
  if (!existsSync(dir)) return fileList;

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);

    // Skip common non-content directories
    if (
      entry === 'node_modules' ||
      entry === '.git' ||
      entry === '.docusaurus' ||
      entry === 'build' ||
      entry === 'dist'
    ) {
      continue;
    }

    if (statSync(full).isDirectory()) {
      walkDir(full, fileList);
    } else {
      fileList.push(full);
    }
  }

  return fileList;
}

/** Scan a docs directory for .md/.mdx files, sorted alphabetically. */
function scanDocsDir(dir: string): string[] {
  if (!existsSync(dir)) return [];

  const files: string[] = [];

  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);

    if (statSync(full).isDirectory()) {
      files.push(...scanDocsDir(full));
    } else {
      const ext = extname(entry).toLowerCase();
      if (ext === '.md' || ext === '.mdx') {
        files.push(full);
      }
    }
  }

  return files;
}

/** Copy a directory tree from src to dest, creating directories as needed. */
function copyDirRecursive(src: string, dest: string): void {
  if (!existsSync(src)) return;

  mkdirSync(dest, { recursive: true });

  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);

    if (statSync(srcPath).isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

// ---------------------------------------------------------------------------
// Main migration orchestrator
// ---------------------------------------------------------------------------

/**
 * Migrate a Docusaurus documentation project to Tome.
 *
 * @param sourceDir  Root of the Docusaurus project (where docusaurus.config.js lives).
 * @param outDir     Destination directory for the Tome project.
 * @param options    Optional flags - `dryRun` skips writing to disk.
 */
export async function migrateFromDocusaurus(
  sourceDir: string,
  outDir: string,
  options?: { dryRun?: boolean },
): Promise<MigrationResult> {
  const warnings: string[] = [];
  const convertedFiles: string[] = [];
  const dryRun = options?.dryRun ?? false;

  // 1. Read and parse docusaurus.config.js or docusaurus.config.ts --------
  const configJsPath = join(sourceDir, 'docusaurus.config.js');
  const configTsPath = join(sourceDir, 'docusaurus.config.ts');
  const configPath = existsSync(configTsPath) ? configTsPath : configJsPath;

  let docConfig: DocusaurusConfig = {};
  if (existsSync(configPath)) {
    const configContent = readFileSync(configPath, 'utf-8');
    docConfig = parseDocusaurusConfig(configContent);
  } else {
    warnings.push('No docusaurus.config.js or docusaurus.config.ts found');
  }

  // 2. Read and parse sidebars.js -----------------------------------------
  const sidebarsJsPath = join(sourceDir, 'sidebars.js');
  const sidebarsJsonPath = join(sourceDir, 'sidebars.json');
  const sidebarsPath = existsSync(sidebarsJsPath)
    ? sidebarsJsPath
    : existsSync(sidebarsJsonPath)
      ? sidebarsJsonPath
      : null;

  let sidebars: SidebarsConfig = {};
  const docsDir = join(sourceDir, 'docs');

  if (sidebarsPath) {
    const sidebarsContent = readFileSync(sidebarsPath, 'utf-8');
    if (sidebarsPath.endsWith('.json')) {
      try {
        sidebars = JSON.parse(sidebarsContent) as SidebarsConfig;
      } catch {
        warnings.push('Failed to parse sidebars.json');
      }
    } else {
      sidebars = parseSidebarsConfig(sidebarsContent);
    }
  }

  // 3. Convert config -----------------------------------------------------
  const tomeConfig = convertDocusaurusConfig(docConfig, sidebars, docsDir);

  // 4. Collect and convert content files (.mdx / .md) ---------------------
  const contentDir = existsSync(docsDir) ? docsDir : sourceDir;
  const allFiles = walkDir(contentDir);
  const contentFiles = allFiles.filter((f) => {
    const ext = extname(f).toLowerCase();
    return ext === '.mdx' || ext === '.md';
  });

  const pagesDir = join(outDir, 'pages');

  for (const filePath of contentFiles) {
    const raw = readFileSync(filePath, 'utf-8');
    const rel = relative(contentDir, filePath);

    // Preserve frontmatter
    const { data: frontmatter, content: body } = matter(raw);

    // Convert Docusaurus-specific frontmatter
    if (frontmatter.sidebar_label && !frontmatter.title) {
      frontmatter.title = frontmatter.sidebar_label;
    }
    // Clean up Docusaurus-specific frontmatter keys
    delete frontmatter.sidebar_label;
    delete frontmatter.sidebar_position;
    delete frontmatter.slug;
    delete frontmatter.custom_edit_url;

    const { converted, hasJsx } = convertDocusaurusContent(body);

    // Check for components that need manual attention
    if (/<BrowserWindow[\s>]/i.test(converted)) {
      warnings.push(
        `${rel}: contains <BrowserWindow> which may need manual conversion`,
      );
    }
    if (/<DocCardList[\s>]/i.test(converted)) {
      warnings.push(
        `${rel}: contains <DocCardList> which may need manual conversion`,
      );
    }

    // Reconstruct file with frontmatter
    const outContent = matter.stringify(converted, frontmatter);

    // Determine output extension
    const outFileName = hasJsx
      ? rel.replace(/\.md$/, '.mdx')
      : rel;
    const outPath = join(pagesDir, outFileName);

    if (!dryRun) {
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, outContent, 'utf-8');
    }

    convertedFiles.push(outFileName);
  }

  // 5. Copy static assets -------------------------------------------------
  if (!dryRun) {
    const publicDir = join(outDir, 'public');

    // Docusaurus static assets live in static/
    const staticDir = join(sourceDir, 'static');
    if (existsSync(staticDir)) {
      copyDirRecursive(staticDir, join(publicDir, 'static'));
    }
  }

  // 6. Generate tome.config.js --------------------------------------------
  if (!dryRun) {
    mkdirSync(outDir, { recursive: true });

    const configContent = [
      '/** @type {import("@tomehq/core").TomeConfig} */',
      `export default ${JSON.stringify(tomeConfig, null, 2)};`,
      '',
    ].join('\n');

    writeFileSync(join(outDir, 'tome.config.js'), configContent, 'utf-8');
  }

  // 7. Build result -------------------------------------------------------
  return {
    pages: convertedFiles.length,
    redirects: 0,
    warnings,
    convertedFiles,
  };
}
