name = "tome-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[[r2_buckets]]
binding = "TOME_BUCKET"
bucket_name = "tome-sites"

[[d1_databases]]
binding = "TOME_DB"
database_name = "tome-db"
database_id = "7da6a731-e26b-4f08-8563-9107269966a1"

[vars]
ENVIRONMENT = "production"
